# Generated by Django 3.2.5 on 2021-11-14 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workout_blog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workout',
            name='image',
        ),
    ]
