# Generated by Django 3.2.5 on 2021-11-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_blog', '0002_remove_workout_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout',
            new_name='workout_metcon',
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_skills',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='workout',
            name='workout_weightlifting',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
