# Generated by Django 3.2.5 on 2021-11-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_blog', '0003_auto_20211114_1502'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workout',
            old_name='workout_metcon',
            new_name='metcon_workout',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_skills',
            new_name='skills_workout',
        ),
        migrations.RenameField(
            model_name='workout',
            old_name='workout_weightlifting',
            new_name='weightlifting_workout',
        ),
        migrations.AddField(
            model_name='workout',
            name='metcon_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='skills_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='workout',
            name='weightlifting_title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
