# Generated by Django 3.2.5 on 2021-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout_blog', '0004_auto_20211114_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workout',
            name='metcon_workout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='skills_workout',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='workout',
            name='weightlifting_workout',
            field=models.TextField(blank=True),
        ),
    ]
