# Generated by Django 3.2.5 on 2021-11-02 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_product_shoe_sizes'),
        ('checkout', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='OrderLineTime',
            new_name='OrderLineItem',
        ),
    ]
