# Generated by Django 3.2.5 on 2021-11-11 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_productreview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
