# Generated by Django 3.2.5 on 2021-11-11 16:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_productreview_rating'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productreview',
            options={'ordering': ['-review_date'], 'verbose_name_plural': 'Product Reviews'},
        ),
    ]
