# Generated by Django 3.2.5 on 2021-11-14 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_alter_product_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='review',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='productreview',
            name='title',
            field=models.CharField(default='', max_length=254, null=True),
        ),
    ]
